### ISSUE TITLE
incomplete ContrastMemory_queue

### ISSUE THREAD

**Issue by songyonger** [Lechatelia/CRCD#1]
It seems that the Class ContrastMemory_queue is incomplete and it does not carry out relation contrastive learning.

**Comment by Lechatelia** [comment]
yeah， I used it for early experiments, which increases the negative sampling by using the queue to store features.
However, It did not work in my experiments. Thus,  I do not include this code combining queuing features and contrastive learning.

**Comment by songyonger** [comment]
Thanks for your replies, another question, the relation generator in current code is not a network described in your paper, have you tried relevant experiments?

**Comment by Lechatelia** [comment]
1. adding to the first question
For cifar,  features from all samples are stored in the local GPU directly.
For Imagenet, I store all features by using 8 GPUs distributedly.
2.  the second question
Since I implement this code after the checkout of SenseTime's intern.  I did not back up the code and did not use the final relation module. But I remember that the liner layer and MLP can have similar results. But MLP has more parameters and can have slightly better results.
